Repository dassana-io/web-components, pull requests merged in 2021-08, with the labels that each got.

#436 enhancement #435 - [Carousel]: Add left and right arrows
  package-lock.json
  package.json
  src/components/Carousel/Bullets.tsx
  src/components/Carousel/index.tsx
Labels: enhancement, patch

#437 v0.11.28 -> v0.11.29
  package-lock.json
  package.json
  src/components/Carousel/Bullets.tsx
  src/components/Carousel/index.tsx
Labels: enhancement, patch

#441 enhancement #440 - Default to altText when icon link is broken
  src/__snapshots__/storybook.test.ts.snap
  src/components/Icon/index.tsx
  src/components/Table/fixtures/7_sample_data.ts
  src/components/Table/utils.tsx
Labels: enhancement, minor

#444 feat #443 - Tab enhancements for context hub
  package.json
  src/components/Filters/FiltersSummary.tsx
  src/components/Tabs/Tab.tsx
  src/components/Tabs/TabPane.tsx
  src/components/Tabs/index.tsx
Labels: enhancement, patch

#449 fix #448 - Fix icon error handling for icon with label
  src/components/Icon/index.tsx
  src/components/Table/IconCell.tsx
Labels: bug, patch

#450 fix #448 - Fix icon error handling
  src/components/Icon/index.tsx
Labels: bug, patch

#447 v0.11.29 -> v0.11.30
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Filters/FiltersSummary.tsx
  src/components/Icon/index.tsx
  src/components/Table/IconCell.tsx
  src/components/Table/fixtures/7_sample_data.ts
  src/components/Table/utils.tsx
  src/components/Tabs/Tab.tsx
  src/components/Tabs/TabPane.tsx
  src/components/Tabs/index.tsx
Labels: enhancement, patch

#439 feat #438 - Code Editor: Swap out prism with ace editor to support edit mode
  package-lock.json
  package.json
  rollup.config.ts
  src/__snapshots__/storybook.test.ts.snap
  src/components/Code/Code.stories.tsx
  src/components/Code/index.tsx
  src/components/Code/prism.css
  src/components/Code/utils.ts
  src/components/Form/Form.stories.tsx
  src/components/Form/FormSubmitButton/index.tsx
  src/components/Logs/index.tsx
  src/components/ScrollableSection/Section.stories.tsx
  src/components/Timeline/Separator.tsx
Labels: patch, feature

#451 v0.11.30 -> v0.11.31
  package-lock.json
  package.json
  rollup.config.ts
  src/__snapshots__/storybook.test.ts.snap
  src/components/Code/Code.stories.tsx
  src/components/Code/index.tsx
  src/components/Code/prism.css
  src/components/Code/utils.ts
  src/components/Form/Form.stories.tsx
  src/components/Form/FormSubmitButton/index.tsx
  src/components/Logs/index.tsx
  src/components/ScrollableSection/Section.stories.tsx
  src/components/Timeline/Separator.tsx
Labels: enhancement, patch

#453 feat #452 - Allow button color to be customized
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Button/Button.stories.tsx
  src/components/Button/index.tsx
  src/components/Button/utils.ts
Labels: enhancement, patch

#454 v0.11.31 -> v0.11.32
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Button/Button.stories.tsx
  src/components/Button/index.tsx
  src/components/Button/utils.ts
Labels: enhancement, patch

#456 fix #455 - Fix hover styles on customized color button
  package.json
  src/components/Button/utils.ts
Labels: bug, patch

#457 v0.11.32 -> v0.11.33
  package.json
  src/components/Button/utils.ts
Labels: bug, patch
