Repository dassana-io/web-components, pull requests merged in 2021-09, with the labels that each got.

#467 chore #466 - [Code] Expose onLoad prop for AceEditor
  package.json
  src/components/Code/index.tsx
Labels: patch, chore

#469 fix #468 - Code: copy bug
  src/components/Code/index.tsx
Labels: bug, patch

#470 v0.11.35 -> v0.11.36
  package.json
  src/components/Code/index.tsx
Labels: bug, patch, chore

#472 enhancement #471 - [Tabs] Expose onTabChange method
  package.json
  src/components/Code/index.tsx
  src/components/Tabs/index.tsx
Labels: enhancement, patch

#473 v0.11.36 -> v0.11.37
  package.json
  src/components/Code/index.tsx
  src/components/Tabs/index.tsx
Labels: enhancement, patch

#477 feat #476 - Update RadioGroup component styles
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Form/FormRadioGroup/index.tsx
  src/components/RadioGroup/RadioGroupSkeleton.tsx
  src/components/RadioGroup/index.tsx
  src/components/RadioGroup/utils.ts
Labels: enhancement, patch

#479 fix #478 - [Code] Update highlight color
  package.json
  src/components/Code/utils.ts
Labels: bug, patch

#480 v0.11.37 -> v0.11.39
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Code/utils.ts
  src/components/Form/FormRadioGroup/index.tsx
  src/components/RadioGroup/RadioGroupSkeleton.tsx
  src/components/RadioGroup/index.tsx
  src/components/RadioGroup/utils.ts
Labels: patch, chore

#481 v0.11.39 -> v0.11.40
  package.json
  src/components/Code/utils.ts
Labels: bug, patch

#482 feat #475 - Code Diff Viewer
  package-lock.json
  package.json
  rollup.config.ts
  src/__snapshots__/storybook.test.ts.snap
  src/components/Code/utils.ts
  src/components/CodeDiffViewer/CodeDiffViewer.stories.tsx
  src/components/CodeDiffViewer/Prism.css
  src/components/CodeDiffViewer/index.tsx
  src/components/CodeDiffViewer/styles.ts
  src/components/index.ts
Labels: patch, feature

#485 enhancement #484 - Allow ReactNode to be passed as message
  src/components/NotificationV2/Notification.tsx
  src/components/NotificationV2/utils.ts
Labels: enhancement, patch

#486 v0.11.40 -> v0.11.41
  package-lock.json
  package.json
  rollup.config.ts
  src/__snapshots__/storybook.test.ts.snap
  src/components/Code/utils.ts
  src/components/CodeDiffViewer/CodeDiffViewer.stories.tsx
  src/components/CodeDiffViewer/Prism.css
  src/components/CodeDiffViewer/index.tsx
  src/components/CodeDiffViewer/styles.ts
  src/components/NotificationV2/Notification.tsx
  src/components/NotificationV2/utils.ts
  src/components/index.ts
Labels: enhancement, patch

#488 enhancement #487 - Web authoring polishing
  package-lock.json
  package.json
  src/components/Button/utils.ts
  src/components/CodeDiffViewer/styles.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/__tests__/Modal.test.tsx
  src/components/Modal/utils.ts
Labels: enhancement, patch

#489 v0.11.41 -> v0.11.42
  package-lock.json
  package.json
  src/components/Button/utils.ts
  src/components/CodeDiffViewer/styles.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/__tests__/Modal.test.tsx
  src/components/Modal/utils.ts
Labels: enhancement, patch

#491 enhancement #490 - [Notifications] Standalone mode
  package.json
  src/components/NotificationV2/NotificationV2.stories.tsx
  src/components/NotificationV2/utils.ts
Labels: enhancement, patch

#492 v0.11.42 -> v0.11.43
  package.json
  src/components/NotificationV2/NotificationV2.stories.tsx
  src/components/NotificationV2/utils.ts
Labels: enhancement, patch
