Repository dassana-io/web-components, pull requests merged in 2022-03, with the labels that each got.

#589 enhancement #587, #588 - Enhancements for Sample App
  package.json
  src/components/Banner/index.tsx
  src/components/Code/index.tsx
Labels: enhancement, patch

#591 enhancement #590 - RadioGroupButton light theme colors
  package-lock.json
  package.json
  src/components/RadioButtonGroup/utils.ts
Labels: enhancement, patch

#593 enhancement #592 - Progressbar classes prop should be optional
  package.json
  src/components/ProgressBar/index.tsx
Labels: enhancement, patch

#595 enhancement #594 - Allow hiding of Error404 button
  package-lock.json
  package.json
  src/components/Pages/Error404.tsx
Labels: enhancement, patch

#597 fix #596 - Fix table skeleton loader not being properly memo-ized
  package.json
  src/components/Table/TableSkeleton.tsx
Labels: bug, patch

#602 enhancement #601 - [Table] Add prop for date formatter
  package.json
  src/components/Table/types.ts
  src/components/Table/utils.tsx
Labels: enhancement, patch

#603 feat #600 - Pagination component
  .storybook/main.js
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Form/FormChipInput/index.tsx
  src/components/Input/Input.test.tsx
  src/components/Input/index.tsx
  src/components/Paginate/Paginate.stories.tsx
  src/components/Paginate/index.tsx
  src/components/Paginate/styles.ts
  src/components/Select/SingleSelect/utils.ts
  src/components/Table/utils.tsx
  src/components/index.ts
Labels: patch, feature

#605 fix #604 - [Markdown] Fix broken styles
  package.json
  src/components/Link/utils.ts
  src/components/Markdown/index.tsx
Labels: bug, patch

#607 Disabled IconButton should maintain same border color on hover
  package-lock.json
  package.json
  src/components/IconButton/utils.ts
Labels: enhancement, patch

#608 fix #604 - Update markdown styles
  package.json
  src/components/Banner/index.tsx
  src/components/Markdown/index.tsx
  src/components/Markdown/styles.ts
Labels: bug, patch
