Repository dassana-io/web-components, pull requests merged in 2022-02, with the labels that each got.

#558 fix #555, #556, #557 - Batch Fixes
  package-lock.json
  package.json
  src/components/Code/utils.ts
  src/components/Input/utils.ts
  src/components/Table/styles.ts
Labels: bug, patch

#560 fix #559 - [TableDrawer] Close drawer if table is loading
  package-lock.json
  package.json
  src/components/TableDrawer/TableDrawer.tsx
Labels: bug, patch

#564 fix #561, enhancement #562, #563 - Batch improvements & fixes
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Avatar/index.tsx
  src/components/Code/index.tsx
  src/components/Table/index.tsx
Labels: bug, enhancement, patch

#566 enhancement #565 - Table header color blends in with background in dark mode
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Table/TableSkeleton.tsx
  src/components/Table/index.tsx
  src/components/Table/styles.ts
  src/components/Table/types.ts
Labels: enhancement, patch

#569 fix #567, #568 - Table fixes
  package.json
  src/components/Table/CellWithTooltip.tsx
  src/components/Table/types.ts
  src/components/Table/utils.tsx
  src/components/TableDrawer/TableDrawer.tsx
Labels: bug, patch

#572 fix #571 - [TableSkeleton] Keep table cell skeleton width consistent between rerenders
  package.json
  src/components/Table/TableSkeleton.tsx
Labels: bug, patch

#576 fix #575 - [Table] Fix cell data not loading for keys with double quotes and spaces
  package.json
  src/components/utils.ts
Labels: bug, patch

#577 fix #575 - Add key formatter for columns
  package-lock.json
  package.json
  src/components/Table/types.ts
  src/components/Table/utils.tsx
  src/components/utils.ts
Labels: bug, patch

#574 enhancement #573 - Start using profile v2 APIs in the FTU flow
  package-lock.json
  package.json
  src/components/Filters/FilterUnit/ValuesMultiSelect/utils.ts
  src/components/Form/FormTimezone/index.tsx
  src/components/Select/BaseSelect.tsx
  src/components/Select/MultiSelect/index.tsx
  src/components/Select/MultiSelect/utils.ts
  src/components/Select/SingleSelect/types.ts
  src/components/Timezone/index.tsx
Labels: enhancement, patch

#579 Change progression shortcut for role selection
  package-lock.json
  package.json
  src/components/MultipleChoice/BaseMultipleChoice.tsx
  src/components/MultipleChoice/MultipleChoiceItem.tsx
  src/components/MultipleChoice/types.ts
Labels: bug, patch

#581 enhancement #580 - [Table] Add prop for disable row click
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Markdown/index.tsx
  src/components/Table/index.tsx
Labels: enhancement, patch

#583 fix #582 - [Table] Fix disabled row click color
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Table/__tests__/utils.test.tsx
  src/components/Table/index.tsx
  src/components/Table/styles.ts
  src/components/Table/utils.tsx
Labels: bug, patch

#586 enhancement #584, #585 - Table & Code updates
  package.json
  src/components/Code/utils.ts
  src/components/Table/EditableCell.tsx
  src/components/Table/Table.stories.tsx
  src/components/Table/__tests__/utils.test.tsx
  src/components/Table/index.tsx
  src/components/Table/types.ts
  src/components/Table/utils.tsx
  src/components/TableDrawer/TableDrawer.tsx
  src/components/TableDrawer/index.tsx
Labels: enhancement, patch
