Repository dassana-io/web-components, pull requests merged in 2022-01, with the labels that each got.

#532 enhancement #531 - Form & Wizard Improvements
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Form/FormCheckbox/index.tsx
  src/components/Form/FormSubmitButton/index.tsx
  src/components/Form/index.tsx
  src/components/Tooltip/utils.ts
  src/components/Wizard/index.tsx
Labels: enhancement, patch

#536 enhancement #535 - [JSONPathPIcker] Read only mode
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/JSONPathPicker/index.tsx
  src/components/JSONPathPicker/styles.ts
  src/components/JSONPathPicker/utils.tsx
Labels: enhancement, patch

#538 fix #537 - [Notification] Increase z-index so it shows over modals
  package.json
  src/components/NotificationV2/index.tsx
Labels: bug, patch

#545 fix #543, feat #544 - Truncated Component and EditableField Changes
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/EditableField/index.tsx
  src/components/Input/Input.test.tsx
  src/components/Input/index.tsx
  src/components/Input/utils.ts
  src/components/TruncatedText/TruncatedText.stories.tsx
  src/components/TruncatedText/index.tsx
  src/components/index.ts
Labels: enhancement, patch, feature

#548 fix #547 - Remove keydown handler for form
  package.json
  src/components/Form/index.tsx
Labels: bug, patch

#550 enhancement #549 - Add prop to persist banner state
  package-lock.json
  package.json
  src/components/Banner/index.tsx
Labels: enhancement, patch

#554 enhancement #553 - Component updates for query builder
  package-lock.json
  package.json
  src/components/Accordion/Animate.tsx
  src/components/Code/index.tsx
  src/components/CodeDiffViewer/index.tsx
  src/components/DateRangeInput/index.tsx
  src/components/Input/index.tsx
  src/components/Table/TableSkeleton.tsx
Labels: enhancement, patch
