Repository dassana-io/web-components, pull requests merged in 2022-07, with the labels that each got.

#702 fix #701 - [Input] Fix unreadable text color on safari
  package-lock.json
  package.json
  src/components/Input/utils.ts
Labels: bug, patch

#704 chore #703 - Fix chromatic build issues
  package-lock.json
  package.json
  src/components/Code/Code.stories.tsx
Labels: patch, chore

#709 enhancement #708 - Add containerClasses to FormToggle
  package-lock.json
  package.json
  src/components/Form/FormToggle/index.tsx
Labels: enhancement, patch

#711 enhancement #710 - Split Tabs left and right
  package-lock.json
  package.json
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/index.tsx
Labels: enhancement, patch
