Repository dassana-io/web-components, pull requests merged in 2022-08, with the labels that each got.

#715 enhancement #714 - [Table] Selectable Rows
  package-lock.json
  package.json
  src/components/Table/index.tsx
  src/components/Table/styles.ts
  src/components/Table/utils.tsx
Labels: enhancement, patch

#717 fix #716 - [Table] Fix checkbox colors
  package-lock.json
  package.json
  src/components/Checkbox/utils.ts
  src/components/Table/styles.ts
Labels: bug, patch

#718 enhancement #719 - FormInput label should accept ReactNode
  package-lock.json
  package.json
  src/components/Form/FieldLabel/index.tsx
  src/components/Form/types.ts
Labels: enhancement, patch

#722 feat #712, #713, #720, #721 - Changes for asset attribution
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/DynamicKVInput/index.tsx
  src/components/Select/BaseSelect.tsx
  src/components/Select/MultiSelect/index.tsx
  src/components/Select/MultiSelect/types.ts
  src/components/Select/SingleSelect/types.ts
  src/components/SplitPane/Pane.tsx
  src/components/SplitPane/Resizer.tsx
  src/components/SplitPane/SplitPaneContext.tsx
  src/components/SplitPane/index.tsx
  src/components/SplitPane/utils.ts
  src/components/Table/Table.stories.tsx
  src/components/Table/fixtures/0_sample_data.ts
  src/components/Table/index.tsx
  src/components/Table/styles.ts
  src/components/Table/types.ts
  src/components/Table/utils.tsx
  src/components/index.ts
Labels: enhancement, patch, feature

#725 enhancement #724 - [Table] Add ability to pass ReactNode for select option for in row editing
  package-lock.json
  package.json
  src/components/Form/FormSelect/index.tsx
  src/components/Form/types.ts
  src/components/Table/EditableCell.tsx
  src/components/Table/index.tsx
  src/components/Table/types.ts
  src/components/Table/utils.tsx
  src/components/assets/styles/styleguide.ts
Labels: enhancement, patch

#727 enhancement #723, #726 - Changes to Filter V1 for dashboard and findings
  package-lock.json
  package.json
  src/components/Filters/BaseFilters.tsx
  src/components/Filters/FilterPopover.tsx
  src/components/Filters/FilterUnit/ValuesInput/index.tsx
  src/components/Filters/FilterUnit/ValuesInput/types.ts
  src/components/Filters/FilterUnit/ValuesMultiSelect/ServerSide.tsx
  src/components/Filters/FilterUnit/index.tsx
  src/components/Filters/Filters.stories.tsx
  src/components/Filters/FiltersContext.ts
  src/components/Filters/ServerSideFilters/index.tsx
  src/components/Filters/ServerSideFilters/utils.ts
  src/components/Filters/fixtures/0_sample_data.ts
  src/components/Filters/types.ts
  src/components/Filters/utils.ts
  src/components/Form/FormInput/index.tsx
  src/components/Select/MultiSelect/index.tsx
Labels: enhancement, patch

#729 fix #728 - [Filters V1] Fix infinite loop in server side filters
  package-lock.json
  package.json
  src/components/Filters/ServerSideFilters/index.tsx
Labels: bug, patch
