Repository dassana-io/web-components, pull requests merged in 2022-10, with the labels that each got.

#746 chore #745 - Table type updates
  package-lock.json
  package.json
  src/components/Table/types.ts
  src/components/Table/utils.tsx
Labels: patch, chore

#748 enhancement #747 - Show additional info underneath table
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Table/index.tsx
  src/components/Table/styles.ts
Labels: enhancement, patch

#750 fix #749 - [Split Pane] Disable text highlighting when resizing
  package-lock.json
  package.json
  src/components/SplitPane/index.tsx
Labels: bug, patch

#752 enhancement #751 - Table additionalInfo prop should accept ReactNode
  package-lock.json
  package.json
  src/components/Table/index.tsx
Labels: enhancement, patch

#754 bugfix #753 - Critical should be purple
  package-lock.json
  package.json
  src/components/RiskIndicator/index.tsx
  src/components/Table/types.ts
Labels: bug, patch

#756 enhancement #755 - Allow command-all text selection BaseSelect
  package-lock.json
  package.json
  src/components/Select/BaseSelect.tsx
Labels: enhancement, patch

#758 fix #757 - [Filters] onFilterSuggest is called with stale data
  package-lock.json
  package.json
  src/components/Filters/ServerSideFilters/index.tsx
  src/components/Filters/ServerSideFilters/utils.ts
Labels: bug, patch

#760 enhancement #759 - [Banner] Update banner for use with preferences
  package-lock.json
  package.json
  src/components/Banner/Banner.stories.tsx
  src/components/Banner/index.tsx
  src/components/Banner/utils.ts
  src/components/Select/BaseSelect.tsx
Labels: enhancement, patch
