Repository dassana-io/web-components, pull requests merged in 2022-09, with the labels that each got.

#731 enhancement #730 - Add more colors
  package-lock.json
  package.json
  src/components/assets/styles/colors.ts
Labels: enhancement, patch

#734 fix #733 - [Filters] Clear options between filters
  package-lock.json
  package.json
  src/components/Filters/FilterUnit/ValuesMultiSelect/ServerSide.tsx
  src/components/Filters/ServerSideFilters/utils.ts
  src/components/Select/MultiSelect/index.tsx
  src/components/Select/MultiSelect/types.ts
Labels: bug, patch

#736 fix #735 - [Filters V1] Fix server side options not populating on first load
  package-lock.json
  package.json
  src/components/Filters/FilterUnit/ValuesMultiSelect/ServerSide.tsx
Labels: bug, patch

#738 feat #737 - Updated progress bar component
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/ProgressBar/index.tsx
Labels: patch, feature

#740 enhancement #739 - [Filters] Add clear filters callback
  package-lock.json
  package.json
  src/components/Filters/BaseFilters.tsx
  src/components/Filters/FiltersContext.ts
  src/components/Filters/types.ts
Labels: enhancement, patch

#743 enhancement #742 - [Filters] Remove operator and fix key disable
  package-lock.json
  package.json
  src/components/Filters/FilterUnit/index.tsx
  src/components/Filters/styles.ts
Labels: enhancement, patch
