Repository dassana-io/web-components, pull requests merged in 2022-05, with the labels that each got.

#655 enhancement #654 - [Query Display] Header enhancements
  package.json
  src/components/IconButton/index.tsx
  src/components/QueryDisplay/index.tsx
Labels: enhancement, patch

#657 fix #656 - Fix chip input values not showing up as tags
  package-lock.json
  package.json
  src/components/ChipInput/index.tsx
Labels: bug, patch

#661 enhancement #658, #660, fix #659 - Enhancements and fixes for notification rules
  package-lock.json
  package.json
  src/components/Form/index.tsx
  src/components/IconButton/index.tsx
  src/components/Table/types.ts
  src/components/Table/utils.tsx
Labels: bug, enhancement, patch

#664 fix #662, enhancement #663 - Search V3 Fixes
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Paginate/index.tsx
  src/components/Table/utils.tsx
Labels: bug, enhancement, patch

#667 fix #665, #666 - Table and form fixes
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/ChipInput/index.tsx
  src/components/ChipInput/utils.ts
  src/components/Table/__tests__/Table.test.tsx
  src/components/Table/__tests__/utils.test.tsx
  src/components/Table/index.tsx
  src/components/Table/types.ts
  src/components/Table/utils.tsx
Labels: bug, patch

#672 fix #671 - [Paginate] Reset to first page on page size change or if data length changes
  package-lock.json
  package.json
  src/components/Paginate/index.tsx
Labels: bug, patch

#674 fix #673 - MultiSelect search should match everything
  package-lock.json
  package.json
  src/components/Select/MultiSelect/index.tsx
Labels: bug, patch

#676 enhancement #675 - Render tags full width
  package-lock.json
  package.json
  src/components/ChipInput/index.tsx
  src/components/ChipInput/utils.ts
Labels: enhancement, patch

#678 enhancement #677 - [ChipInput] Allow tags to be formatted
  package-lock.json
  package.json
  src/components/ChipInput/index.tsx
Labels: enhancement, patch

#680 enhancement #679 - Allow unsorted multiselect options
  package-lock.json
  package.json
  src/components/Select/MultiSelect/index.tsx
  src/components/Select/MultiSelect/types.ts
Labels: enhancement, patch
