Repository dassana-io/web-components, pull requests merged in 2022-04, with the labels that each got.

#609 feat #598 - Query Display Component
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Markdown/index.tsx
  src/components/Markdown/styles.ts
  src/components/Paginate/index.tsx
  src/components/QueryDisplay/QueryDisplay.stories.tsx
  src/components/QueryDisplay/index.tsx
  src/components/QueryDisplay/styles.ts
  src/components/Tabs/index.tsx
  src/components/Tabs/utils.ts
  src/components/index.ts
Labels: patch, feature

#611 enhancement #610 - Fix tooltip arrow background color
  package-lock.json
  package.json
  src/components/Tooltip/utils.ts
Labels: enhancement, patch

#613 enhancement #612 - [Tabs] Add prop to control transition duration
  package.json
  src/components/Paginate/index.tsx
  src/components/Tabs/TabPane.tsx
  src/components/Tabs/index.tsx
Labels: enhancement, patch

#615 enhancement #614 - [Tabs] Expose tabConfg in tabsRef
  package.json
  src/components/Tabs/index.tsx
Labels: enhancement, patch

#617 enhancement #616 - [QueryDisplay] Add loading prop
  package.json
  src/components/QueryDisplay/index.tsx
Labels: enhancement, patch

#619 enhancement #618 - [Query Builder] Allow ReactNode to be passed for name
  package.json
  src/components/QueryDisplay/index.tsx
Labels: enhancement, patch

#621 enhancement #620 - Default timezone value
  package-lock.json
  package.json
  src/components/Timezone/index.tsx
Labels: enhancement, patch

#623 enhancement #622 - Link target in Markdown
  package-lock.json
  package.json
  src/components/Markdown/index.tsx
Labels: enhancement, patch

#625 enhancement #624 - [Query Display]: Add prop for name container classes
  package.json
  src/components/QueryDisplay/index.tsx
Labels: enhancement, patch

#627 enhancement #626 - [Query Display] Allow expandable to be configured by a prop
  package.json
  src/components/EditableField/index.tsx
  src/components/QueryDisplay/index.tsx
Labels: enhancement, patch

#629 enhancement #628 - [Toggle] Update active color
  package.json
  src/components/Toggle/utils.ts
Labels: enhancement, patch

#631 fix #630 - Link underline inconsistent between themes
  package-lock.json
  package.json
  src/__snapshots__/storybook.test.ts.snap
  src/components/Link/index.tsx
  src/components/Link/utils.ts
Labels: bug, patch

#635 enhancement #634 - [EditableField] Add unsaved value styles
  package.json
  src/components/EditableField/index.tsx
Labels: enhancement, patch

#633 fix #632 - Fix QueryDisplay component opening duplicate tabs
  package-lock.json
  src/components/QueryDisplay/index.tsx
Labels: bug, patch

#637 v0.12.57 -> v0.12.58
  package-lock.json
  package.json
Labels: patch, chore

#639 enhancement #638 - [Tabs] Expose activeIndex in tabs ref
  package-lock.json
  package.json
  src/components/Tabs/index.tsx
Labels: enhancement, patch

#642 enhancement #640, fix #641 - EditableField and ShortcutMicrocopy Updates
  package.json
  src/components/EditableField/index.tsx
  src/components/ShortcutMicrocopy/index.tsx
  src/components/ShortcutMicrocopy/types.ts
Labels: bug, enhancement, patch

#644 enhancement #643 - Code editor should allow `minLines`
  package-lock.json
  package.json
  src/components/Code/index.tsx
Labels: enhancement, patch

#646 enhancement #645 - [EditableField] Add ability to auto select on focus
  package.json
  src/components/EditableField/index.tsx
  src/components/Input/index.tsx
Labels: enhancement, patch

#649 fix #648 - Links not getting underlined in markdown
  package-lock.json
  package.json
  src/components/Markdown/Markdown.stories.tsx
  src/components/Markdown/index.tsx
Labels: bug, patch

#650 fix #648 - Markdown link underline style for both dark and light themes
  package-lock.json
  package.json
  src/components/Markdown/index.tsx
  src/components/Markdown/styles.ts
Labels: bug, patch
