Repository dassana-io/web-components, pull requests merged in 2023-07, with the labels that each got.

#818 chore #817 - Fix vulnerabilities
  package-lock.json
  package.json
Labels: patch, chore

#820 enhancement #819 - Allow empty tab config if add tab callback provided
  package-lock.json
  package.json
  src/components/Tabs/index.tsx
Labels: enhancement, patch

#824 enhancement #823 - Custom add tab render
  package-lock.json
  package.json
  src/components/Tabs/index.tsx
Labels: enhancement, patch

#826 bugfix #825 - [Table] Fix table loader not showing properly on first render
  package-lock.json
  package.json
  src/components/Table/TableSkeleton.tsx
Labels: bug, patch
