Repository dassana-io/web-components, pull requests merged in 2024-02, with the labels that each got.

#873 chore #872 - Upgrade storybook
  .eslintrc.js
  .storybook/main.ts
  package-lock.json
  package.json
Labels: patch, chore

#875 chore #874 - Export pointer events none component
  package-lock.json
  package.json
  src/components/index.ts
Labels: bug, patch

#878 enhancement #877 - [Modal Drawer] Allow inline styles to be passed
  package-lock.json
  package.json
  src/components/Modal/ModalDrawer.tsx
  src/components/Modal/utils.ts
Labels: enhancement, patch
