Repository dassana-io/web-components, pull requests merged in 2024-10, with the labels that each got.

#933 chore #932 - Update rollup to V4
  .storybook/main.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
  rollup.config.ts
  src/components/Accordion/Accordion.stories.tsx
  src/components/Banner/Banner.stories.tsx
  src/components/Button/Button.stories.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/ChipInput/ChipInput.stories.tsx
  src/components/DateInput/DateInput.stories.tsx
  src/components/DateRangeInput/DateRangeInput.stories.tsx
  src/components/Filters/Filters.stories.tsx
  src/components/Form/Form.stories.tsx
  src/components/Form/FormMultipleChoice/FormMultipleChoice.stories.tsx
  src/components/IconButton/IconButton.stories.tsx
  src/components/InfoTip/InfoTip.stories.tsx
  src/components/Input/Input.stories.tsx
  src/components/Link/Link.stories.tsx
  src/components/Markdown/Markdown.stories.tsx
  src/components/Menu/Menu.stories.tsx
  src/components/MiniSidebar/MiniSidebar.stories.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/MultipleChoice/MultipleChoice.stories.tsx
  src/components/Notification/Notification.stories.tsx
  src/components/NotificationV2/NotificationV2.stories.tsx
  src/components/PageLoader/PageLoader.stories.tsx
  src/components/Pages/Error404.stories.tsx
  src/components/Pages/MadeWithLove.stories.tsx
  src/components/Plausible/Plausible.stories.tsx
  src/components/Popover/Popover.stories.tsx
  src/components/PriorityGrid/PriorityGrid.stories.tsx
  src/components/ProgressBar/ProgressBar.stories.tsx
  src/components/QueryDisplay/QueryDisplay.stories.tsx
  src/components/Radio/Radio.stories.tsx
  src/components/RadioButtonGroup/RadioButtonGroup.stories.tsx
  src/components/RiskIndicator/RiskIndicator.stories.tsx
  src/components/SVGImage/SVGImage.stories.tsx
  src/components/ScrollableSection/ScrollableSection.stories.tsx
  src/components/Select/MultiSelect/MultiSelect.stories.tsx
  src/components/Select/SingleSelect/Select.stories.tsx
  src/components/Select/TagsSelect/TagsSelect.stories.tsx
  src/components/ShortcutMicrocopy/ShortcutMicrocopy.stories.tsx
  src/components/Skeleton/Skeleton.stories.tsx
  src/components/Slider/Slider.stories.tsx
  src/components/Table/Table.stories.tsx
  src/components/TableDrawer/TableDrawer.stories.tsx
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tag/Tag.stories.tsx
  src/components/TimeInput/TimeInput.stories.tsx
  src/components/Timeline/Timeline.stories.tsx
  src/components/Timezone/Timezone.stories.tsx
  src/components/Toggle/Toggle.stories.tsx
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/Tree/Tree.stories.tsx
  src/components/TreeSelect/TreeSelect.stories.tsx
  src/components/TreeSelect/index.tsx
  src/components/TruncatedText/TruncatedText.stories.tsx
  src/components/Wizard/Wizard.stories.tsx
Labels: patch, chore

#934 bugfix #933 - Fix types not being declared
  package.json
  rollup.config.ts
  src/components/Modal/__tests__/ModalProvider.test.tsx
Labels: bug, patch

#935 chore #932 - Fix types export
  package-lock.json
  package.json
  rollup.config.ts
Labels: patch, chore

#936 bugfix #932 - Export types correctly from package.json
  package-lock.json
  package.json
Labels: bug, patch

#937 Allow custom dropdown option labels
  package-lock.json
  package.json
  src/components/Select/SingleSelect/types.ts
Labels: enhancement, patch

#940 enhancement #939 - Add customization tooltip to tabs on close
  package-lock.json
  package.json
  src/components/Tabs/Tab.tsx
  src/components/Tabs/index.tsx
Labels: enhancement, patch

#943 enhancement #942 - [Form] Update form input and form multiselect to have configuration loading state
  package-lock.json
  package.json
  src/components/Form/FormInput/index.tsx
  src/components/Form/FormMultiSelect/index.tsx
Labels: enhancement, patch
