Repository dassana-io/web-components, pull requests merged in 2024-07, with the labels that each got.

#908 chore #907 - Update web-utils version
  package-lock.json
  package.json
Labels: patch, chore

#910 enhancement #909 - Date picker component
  package-lock.json
  package.json
  src/components/DateInput/DateInput.stories.tsx
  src/components/DateInput/index.tsx
  src/components/DateInput/styles.ts
  src/components/DateRangeInput/styles.ts
  src/components/Form/FormDateInput/index.tsx
  src/components/Form/index.tsx
  src/components/index.ts
Labels: enhancement, patch

#912 bugfix #911 - [Select] Fix truncated text tooltip not appearing in modal
  src/components/Select/OptionChildren.tsx
  src/components/Select/utils.ts
Labels: bug, patch

#913 0.14.45
  package-lock.json
  package.json
Labels: patch, chore

#915 enhancement #914 - Select option icon default src url
  package.json
  src/components/Icon/index.tsx
  src/components/Select/BaseSelect.tsx
  src/components/Select/OptionChildren.tsx
Labels: enhancement, patch

#917 bugfix #916 - [Table] Fix truncated text tooltip not showing up when table is rendered inside a modal
  package-lock.json
  package.json
  src/components/Table/CellWithTooltip.tsx
  src/components/assets/styles/colors.ts
Labels: bug, patch

#919 enhancement #918 - [Code] Update placeholder font
  package-lock.json
  package.json
  src/components/Code/utils.ts
Labels: enhancement, patch
